Skip element if errors in metadata server
outscale-mdr/cloud-init pull request #1
Opened 2022-05-10 13:47 UTC by outscale-mdr

Right now if some elements are not available in the metadata, the retrieval fails and it crashs. We propose to add the ability to skip some element if necessary.

Use-case: our tags can have invalid URI characters like '/' in the middle. Wewould like to be able to continue if some elements are not available with something like:

```python
def _skip_tags(exception):
    if isinstance(exception, uhelp.UrlError) and exception.code == 404:
        if "meta-data/tags/" in exception.url:
            print(exception.url)
            return True
    return False
data = ec2.get_instance_metadata(
                headers_cb=None,
                skip_cb=_skip_tags
            )
```

2022-05-11 12:19 UTC, outscale-mdr commented
Add Outscale as datasource:

- Outscale machine are identified with a system-uuid starting with `osc`
- We skip error when we retrieve metdata only when it is inside `tags` folder

2022-05-11 12:23 UTC, outscale-mdr commented
TODO List (from [official website](https://cloudinit.readthedocs.io/en/latest/topics/datasources.html)):
- [X] Create a DataSource
- [X] Add tests for the datasource in (`cloudinit/sources/test_<yourplatform>.py`)
- [X] Update ds-identify 
- [X] Add tests of ds-identify
- [X] Update `cloudinit/settings.py`
- [X] Update `cloudinit/apport.py`
- [ ] Update `debian/cloud-init.templates`
- [X] Add Documentation in `doc/datasources/<cloudplatform>.rst`

2022-05-30 13:23 UTC, jerome-jutteau requested changes

2022-05-30 13:23 UTC, jerome-jutteau commented on tests/unittests/sources/test_outscale.py
> +        m_read_dmi_data.return_value = "pas osc dedans"
no osc here

2022-05-30 13:23 UTC, jerome-jutteau commented on tests/unittests/sources/test_outscale.py
> +        m_read_dmi_data.return_value = "oscetlasuite"
osc and other things

2022-05-30 13:23 UTC, jerome-jutteau commented on doc/rtd/topics/datasources/outscale.rst
> +present in cloud-init since 0.7.9.
"is include" ?

2022-09-26 14:19 UTC, closed without merging